DC-366 Plugin: Push latency data to cloud gateway
OpenNMS/opennms-cloud-plugin pull request #72
Opened 2022-11-07 12:52 UTC by FrancescoBuc86

2022-11-17 15:35 UTC, patrick-schweizer reviewed
Nice first PR :-)

A couple of comments:

- I wonder if we should expose _GrpcLogEntryQueue_ to the outside? I think this should be only used by CloudLogService. This way we can change later the implementation of CloudLogService without changing its API.
- I think we should enrich the CloudMock by the new grpc Api and also check in the EndToEndIt to test if logs are send.

2022-11-21 12:41 UTC, patrick-schweizer commented on plugin-common/src/main/java/org/opennms/plugins/cloud/grpc/CloudLogService.java
> +    private static ConcurrentLinkedQueue<LogEntry> logEntryQueue;
I think this can be not static? it is just a member variable. The CloudLogServiceitself is a Singleton via bean definition, no?

2022-11-21 12:41 UTC, patrick-schweizer commented on plugin-common/src/main/java/org/opennms/plugins/cloud/grpc/GrpcExecutionHandler.java
> +    private final CloudLogService grpcLogEntryQueue;
maybe rename variable name?

2022-11-21 12:41 UTC, patrick-schweizer commented on plugin-common/src/main/java/org/opennms/plugins/cloud/util/RunnerWrapper.java
> +    Logger LOG = LoggerFactory.getLogger(RunnerWrapper.class);
can be private static?

2022-11-21 14:04 UTC, freddy61025 requested changes
some minor comments.

2022-11-21 14:04 UTC, freddy61025 commented on plugin-common/src/test/java/org/opennms/plugins/cloud/grpc/CloudLogServiceQueueTest.java
> +    public void entry_is_correctly_inserted_in_queue() {
can we use camelcase?

2022-11-21 14:04 UTC, freddy61025 commented on plugin-common/src/test/java/org/opennms/plugins/cloud/testserver/LogServiceGrpc.java
> +@Slf4j
same here use standardize LOG style.

2022-11-21 14:27 UTC, FrancescoBuc86 commented on it-test/src/test/java/org/opennms/plugins/cloud/ittest/EndToEndIt.java
> +                                "/overlay/sentinel/usr/share/sentinel/etc/org.opennms.netmgt.distributed.datasource.cfg"),
Removed it

2022-11-21 14:27 UTC, FrancescoBuc86 commented on plugin-common/pom.xml
> +            <artifactId>commons-lang3</artifactId>
I'll leave as it is for this time

2022-11-21 14:28 UTC, FrancescoBuc86 commented on plugin-common/src/main/java/org/opennms/plugins/cloud/grpc/CloudLogService.java
> +    private static final int GRPC_BATCH_SIZE = 1000;
good point

2022-11-21 15:23 UTC, FrancescoBuc86 commented on plugin-common/src/main/java/org/opennms/plugins/cloud/grpc/CloudLogService.java
>  @Slf4j
it makes sense, I'll replace the annotation with the getLogger, making sure the capital LOG is used as variable

2022-11-21 15:24 UTC, FrancescoBuc86 commented on plugin-common/src/test/java/org/opennms/plugins/cloud/grpc/CloudLogServiceQueueTest.java
> +    public void entry_is_correctly_inserted_in_queue() {
sure

2022-11-21 15:28 UTC, FrancescoBuc86 commented on plugin-common/src/test/java/org/opennms/plugins/cloud/testserver/LogServiceGrpc.java
> +@Slf4j
Yep

2022-11-21 18:35 UTC, freddy61025 approved these changes
LGTM

2022-11-21 18:37 UTC, merged